spring:
  cloud:
    config:
      fail-fast: true
      server:
        git:
          uri: https://github.com/patkemble/cloud-app-config
  application:
    name: config-service
server:
  port: 8082
